### PR TITLE
New contrast vivi

### PR DESCRIPTION
**Pull request by hww19920718**
add a page to fill the parameters for creating a new contrast

### CODE REVIEW

**Comment by boldpredictions** [comment]
Jenkins Check failed.

**Comment by boldpredictions** [comment]
Jenkins Check failed.

**Comment by boldpredictions** [comment]
Jenkins Check failed.

**Review by Atumu1025 — APPROVED** [review]

**Comment by boldpredictions** [comment]
Jenkins Check failed.

**Comment by boldpredictions** [comment]
Jenkins Check failed.

**Comment by boldpredictions** [comment]
Jenkins Check passed.

**Pull request merged**
